const flags = {
  "arrivalActions": [],
  "feastActions": [],
  "time": 0,
  "inventory": {
    "alcohol": {
      "name": `Calabash of hard liquor`,
      "description": `<p>A calabash full of hard liquor, given to you by Oramui and Terani.</p>`,
    },
    "dolphin": {
      "name": `Pendant`,
      "description": `<p>A pendant shaped like a dolphin, that you discovered by following the advice of Faanarua.</p><p>According to her, it’ll make you an even better swimmer than you already are.</p>`,
    },
    "pearls": {
      "name": `Handful of black pearls`,
      "description": `<p>Pearls of pure black, stolen from the witch.</p><p>So far, you can’t tell anything else about them.</p>`,
    },
    "smokePearls": {
      "name": `Handful of smoke pearls`,
      "description": `<p>Pearls of pure black, stolen from the witch.</p><p>You’ve discovered that crushing one of them underwater will create a thick, impenetrable cloud.</p>`,
    },
    "fruit": {
      "name": `Handful of red fruits`,
      "description": `<p>A handful of red fruits you picked on the advice of a talking crocodile. It said they would help you for the race.</p><p>You can’t tell if the fact that it had previously tried to eat you should make you doubt its sincerity.</p>`,
    },
    "doll": {
      "name": `Wooden figurine`,
      "description": `<p>A figurine that strangely resembles you, created by a talking crocodile out of a tree root. The beast used it as bait in an attempt to make a meal out of you. You don’t know anything else about its properties.</p>`,
    },
    "net": {
      "name": `Witch’s net`,
      "description": `<p>A fishing net that used to belong to a witch. It’s made for capturing humans, not small fish.</p>`,
    },
    "fieryCalabash": {
      "name": `Calabash of doctored alcohol`,
      "description": `<p>Palm wine, now with added spice.</p>`
    },
  },
  "drunk": false,
  "currentIsland": "island-1",
  "visitedIslands": [],
  "eatenByFaanarua": false,
  "talkedWithFaanarua": false,
  "triedToFlee": false,
  "drunkAtTheWitchCup": false,
  "caughtInAWitchNet": false,
  "touchedACursedItem": false,
  "damagedBoat": false,
  "eatenByCrocodile": false,
  "swumUnderWitchIsland": false,
  "wellRested": false,
  "boostedByFruit": false,
  "eatenByRaiahui": false,
  "stabbedToDeath": false,
  "survivedTheTrial": false,
  "toldAboutFaanaruaByRaiahui": false,
  "toldAboutAtollByRaiahui": false,
  "toldAboutLazyOneByAriinea": false,
  "toldAboutFaanaruaByVarenui": false,
  "toldAboutWitchByMonkey": false,
  "watchedKnifeImportance": false,
  "survivedWitchIsland": false,
  "refreshed": false,
  "aVillagerOnCrocodileIsland": false,
  "caughtARaiahui": false,
  "seenRaiahuiTrueForm": false,
  "tastedFruit": false,
  "talkedToPerfectlyUselessDrunkGirl": false,
  "examinedTrialCalabashes": false,
  "playedTheFool": false,
  "flagsBeforeActualTrial": undefined,
  "bleeding": false,
  "weakened": false,
  "gotAHeadStart": false,
  "course": [],
  "targetIsland": undefined,
  "searchedIsland2": false,
  "approachedFaanarua": false,
  "approchedCrocodile": false,
  "encounteredCrocodileAtSea": false,
  "hesitationCounter": 0,
  "wentBeyondIntroduction": false,
  "reachedTheTrial": false,
  "friendlyWithWitch": false,
};

export default flags;
