const flags = {
  "arrivalActions": [],
  "feastActions": [],
  "time": 0,
  "inventory": {
    "alcohol": {
      "name": `Alcool fort`,
      "description": `<p>Une calebasse d’alcool fort offerte par Oramui et Terani.</p>`,
    },
    "dolphin": {
      "name": `Amulette`,
      "description": `<p>Une amulette en forme de dauphin que vous avez déterrée sous les conseils de Faanarua.</p><p>D’après elle, elle fera de vous une encore meilleure nageuse que vous ne l’êtes déjà.</p>`,
    },
    "pearls": {
      "name": `Perles noires`,
      "description": `<p>Des perles d’un noir profond que vous avez volées à la sorcière du lagon.</p><p>Du moins est-ce ainsi qu’elles se présentent à l’œil.</p>`,
    },
    "smokePearls": {
      "name": `Perles de fumée`,
      "description": `<p>Des perles d’un noir profond que vous avez volées à la sorcière du lagon.</p><p>Vous avez découvert que lorsque l’une d’elles est écrasée sous l’eau, elle se dissout aussitôt en un épais nuage absolument opaque.</p>`,
    },
    "fruit": {
      "name": `Fruits rouges`,
      "description": `<p>Un poignée de mystérieux fruits qu’un crocodile parlant vous a conseillé. Il prétend qu’ils vous aideront pour l’épreuve qui vous attend.</p><p>Vous ne sauriez dire si le fait qu’il ait également essayé de vous manger est un argument en la faveur ou en la défaveur de la véracité de cette information.</p>`,
    },
    "doll": {
      "name": `Figurine du crocodile`,
      "description": `<p>Une figurine à votre effigie qu’un crocodile parlant a « sculpté » à partir de racines. Vous ne savez rien d’autre à son sujet si ce n’est qu’il a essayé de s’en servir comme appât dans un piège à votre intention.</p>`,
    },
    "net": {
      "name": `Filet de la sorcière`,
      "description": `<p>Une filet que vous avez récupéré auprès d’une sorcière. Taillé pour la capture d’êtres humains, pas pour celles de petits poissons.</p>`,
    },
    "fieryCalabash": {
      "name": `Calebasse piégée`,
      "description": `<p>Juste un peu de vin de palme, agrémenté de quelques fruits légèrement épicés.</p>`
    },
  },
  "drunk": false,
  "currentIsland": "island-1",
  "visitedIslands": [],
  "eatenByFaanarua": false,
  "talkedWithFaanarua": false,
  "triedToFlee": false,
  "drunkAtTheWitchCup": false,
  "caughtInAWitchNet": false,
  "touchedACursedItem": false,
  "damagedBoat": false,
  "eatenByCrocodile": false,
  "swumUnderWitchIsland": false,
  "wellRested": false,
  "boostedByFruit": false,
  "eatenByRaiahui": false,
  "stabbedToDeath": false,
  "survivedTheTrial": false,
  "toldAboutFaanaruaByRaiahui": false,
  "toldAboutAtollByRaiahui": false,
  "toldAboutLazyOneByAriinea": false,
  "toldAboutFaanaruaByVarenui": false,
  "toldAboutWitchByMonkey": false,
  "watchedKnifeImportance": false,
  "survivedWitchIsland": false,
  "refreshed": false,
  "aVillagerOnCrocodileIsland": false,
  "caughtARaiahui": false,
  "seenRaiahuiTrueForm": false,
  "tastedFruit": false,
  "talkedToPerfectlyUselessDrunkGirl": false,
  "examinedTrialCalabashes": false,
  "playedTheFool": false,
  "flagsBeforeActualTrial": undefined,
  "bleeding": false,
  "weakened": false,
  "gotAHeadStart": false,
  "course": [],
};

export default flags;
